# /***********************************************************************#
# * @file    Makefile                                                     #
# * @brief   sub Makefile file                                            #
# * @history                                                              #
# * Date       Version Author    description                              #
# * ========== ======= ========= =========================================#
# * 2018-07-06 V1.0    weihui.jia   Create                                #
# *                                                                       #
# * @Copyright (C)  2018  original.Co.Ltd all right reserved              #
#************************************************************************/#
# /*@{*/

obj-y += capture_node.o
obj-y += encoder_node.o
obj-y += rtsp_node.o

