# /***********************************************************************#
# * @file    Makefile                                                     #
# * @brief   sub Makefile file                                            #
# * @history                                                              #
# * Date       Version Author    description                              #
# * ========== ======= ========= =========================================#
# * 2018-07-06 V1.0    weihui.jia   Create                                #
# *                                                                       #
# * @Copyright (C)  2018  original.Co.Ltd all right reserved              #
#************************************************************************/#
# /*@{*/

obj-y += media_graph.o
obj-y += sensor_manager.o
obj-y += aiq_controller.o
obj-y += hdr_controller.o
obj-y += rkisp_bridge.o

