[global]
strict init = true
buffer min = 1024
buffer max = 2MB
rotate lock file = self
default format = "%d(%F %T.%l) %-6V [%p] %c %f:%L - %m%n"

[formats]
normal = "%d(%F %T.%l) %-6V [%p] %c %f:%L - %m%n"

[rules]
# Change the level in this rule to DEBUG, INFO, WARN, ERROR, or FATAL.
camera.DEBUG >stdout; normal
camera.DEBUG "logs/camera.log", 10MB * 5; normal
