# /***********************************************************************#
# * @file    Makefile                                                     #
# * @brief   sub Makefile file                                            #
# * @history                                                              #
# * Date       Version Author    description                              #
# * ========== ======= ========= =========================================#
# * 2018-07-06 V1.0    weihui.jia   Create                                #
# *                                                                       #
# * @Copyright (C)  2018  original.Co.Ltd all right reserved              #
#************************************************************************/#
# /*@{*/

obj-y += app/
obj-y += framework/
obj-y += hal/
obj-y += utils/
obj-y += thread/
obj-y += message/
obj-y += codec/
obj-y += network/
obj-y += ai/
