# /***********************************************************************#
# * @file    Makefile                                                     #
# * @brief   sub Makefile file                                            #
# * @history                                                              #
# * Date       Version Author    description                              #
# * ========== ======= ========= =========================================#
# * 2018-07-06 V1.0    weihui.jia   Create                                #
# *                                                                       #
# * @Copyright (C)  2018  original.Co.Ltd all right reserved              #
#************************************************************************/#
# /*@{*/

obj-y += app/
obj-y += callback/
obj-y += core/
obj-y += dma/
obj-y += isp/
obj-y += pipeline/
obj-y += v4l2/
